package com.example.e_commerce_app.model.orders

data class Order(
    val admin_graphql_api_id: String? = null,
    val app_id: Long? = null,
    val billing_address: Any? = null,
    val browser_ip: String? = null,
    val buyer_accepts_marketing: Boolean? = null,
    val cancel_reason: Any? = null,
    val cancelled_at: Any? = null,
    val cart_token: Any? = null,
    val checkout_id: Long? = null,
    val checkout_token: String? = null,
    val client_details: ClientDetails? = null,
    val closed_at: Any? = null,
    val company: Any? = null,
    val confirmation_number: String? = null,
    val confirmed: Boolean? = null,
    val contact_email: String? = null,
    val created_at: String, // Not nullable
    val currency: String? = null, // Made nullable
    val current_subtotal_price: String? = null,
    val current_subtotal_price_set: CurrentSubtotalPriceSet? = null,
    val current_total_additional_fees_set: Any? = null,
    val current_total_discounts: String? = null,
    val current_total_discounts_set: CurrentTotalDiscountsSet? = null,
    val current_total_duties_set: Any? = null,
    val current_total_price: String? = null,
    val current_total_price_set: CurrentTotalPriceSet? = null,
    val current_total_tax: String? = null,
    val current_total_tax_set: CurrentTotalTaxSet? = null,
    val customer: Customer? = null,
    val customer_locale: String? = null,
    val device_id: Any? = null,
    val discount_applications: List<Any>? = null,
    val discount_codes: List<Any>? = null,
    val email: String? = null,
    val estimated_taxes: Boolean? = null,
    val financial_status: String? = null,
    val fulfillment_status: Any? = null,
    val fulfillments: List<Any>? = null,
    val id: Long, // Not nullable
    val landing_site: Any? = null,
    val landing_site_ref: Any? = null,
    val line_items: List<LineItem> = emptyList(),
    val location_id: Long, // Not nullable
    val merchant_of_record_app_id: Any? = null,
    val name: String? = null,
    val note: Any? = null,
    val note_attributes: List<Any>? = null,
    val number: Int? = null,
    val order_number: Int, // Not nullable
    val order_status_url: String? = null,
    val original_total_additional_fees_set: Any? = null,
    val original_total_duties_set: Any? = null,
    val payment_gateway_names: List<Any>? = null,
    val payment_terms: Any? = null,
    val phone: Any? = null,
    val po_number: Any? = null,
    val presentment_currency: String? = null,
    val processed_at: String? = null,
    val reference: String? = null,
    val referring_site: Any? = null,
    val refunds: List<Any>? = null,
    val shipping_address: Any? = null,
    val shipping_lines: List<Any>? = null,
    val source_identifier: String? = null,
    val source_name: String? = null,
    val source_url: Any? = null,
    val subtotal_price: String? = null,
    val subtotal_price_set: SubtotalPriceSet? = null,
    val tags: String? = null,
    val tax_exempt: Boolean? = null,
    val tax_lines: List<Any>? = null,
    val taxes_included: Boolean? = null,
    val test: Boolean? = null,
    val token: String? = null,
    val total_discounts: String? = null,
    val total_discounts_set: TotalDiscountsSet? = null,
    val total_line_items_price: String? = null,
    val total_line_items_price_set: TotalLineItemsPriceSet? = null,
    val total_outstanding: String? = null,
    val total_price: String, // Not nullable
    val total_price_set: TotalPriceSet? = null,
    val total_shipping_price_set: TotalShippingPriceSet? = null,
    val total_tax: String? = null,
    val total_tax_set: TotalTaxSet?=null,
    val total_tip_received: String? = null,
    val total_weight: Int? = null,
    val updated_at: String? = null,
    val user_id: Any? = null
)
